### ISSUE TITLE
Screeps 4.x store changes

### ISSUE THREAD

**Issue by shanemadden** [rustyscreeps/screeps-game-api#253]
Screeps 4.0 deprecates `Creep.carry` and the non-`.store` storage attributes on a number of structures. `CanStoreEnergy` should be removed and all of these structures (and possibly also creeps?) should be added to `HasStore` (removing `ghodium()`/`ghodium_capacity()` from nukers, `mineral_amount()` from labs etc) to move off of the deprecated properties.

**Comment by daboross** [comment]
Sounds good!

I think we'll also want some methods to match [Store.getCapacity(Resource)](https://docs.screeps.com/api/#Store.getCapacity) and getFreeCapacity / getUsedCapacity, since those are new and replace the specific methods like `ghodium / ghodium_capacity`.

Another design question, though: what do we want to do with the `Store` type? We could:

- just stick all the binding methods on `HasStore`, and ignore the existence of `Store`
- add a `Store` type, and replace `HasStore` with:
  ```rust
  trait HasStore {
      fn store(&self) -> Store { ... }
  }
  ```
- add a `Store` type & keep existing `HasStore` methods as well

I'm inclined towards the last option, but any of these or any others could be good.

I'm inclined towards introducing `Store`, but keeping utility methods on `HasStore` as well. It'd mean

**Comment by ASalvail** [comment]
They added a prototype in order to make a unified interface. It feels a lot like a trait already, so my vote goes to sticking everything in `HasStore`.
